common/models/Farm.php
<?php

namespace common\models;

use Yii;
use common\models\Size;

/**
 * This is the model class for table "Farm".
 *
 * @property int $FarmID
 * @property int $Size
 * @property int $Price
 * @property int $SoilReport
 * @property string $Location
 * @property string $Duration
 * @property int $IsDelete
 * @property string $OnDate
 * @property string $UpdatedDate
 *
 * @property Size $size
 * @property Image $soilReport
 * @property FarmImage[] $farmImages
 */
class Farm extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'Farm';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['FarmName','Size', 'Price','Location', 'Duration','OnDate'], 'required'],
            [['Size', 'Price','IsDelete','Stock','AvailableStock'], 'integer'],
            [['Location'], 'string'],
            [['OnDate', 'UpdatedDate'], 'safe'],
            [['Duration'], 'string', 'max' => 20],
            [['Size'], 'exist', 'skipOnError' => true, 'targetClass' => Size::className(), 'targetAttribute' => ['Size' => 'SizeID']],
           // [['SoilReport'], 'exist', 'skipOnError' => true, 'targetClass' => Image::className(), 'targetAttribute' => ['SoilReport' => 'ImageID']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'FarmID' => 'Farm ID',
            'FarmName' => 'Farm Name',
            'Size' => 'Size (sq Ft)',
            'Price' => 'Price',
            'SoilReport' => 'Soil Report',
            'Location' => 'Location',
            'Duration' => 'Duration',
            'IsDelete' => 'Is Delete',
            'OnDate' => 'On Date',
            'UpdatedDate' => 'Updated Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSize()
    {
        return $this->hasOne(Size::className(), ['SizeID' => 'Size']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSoilReport()
    {
        return $this->hasOne(Image::className(), ['ImageID' => 'SoilReport']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFarmImages()
    {
        return $this->hasMany(FarmImage::className(), ['FarmID' => 'FarmID']);
    }
	
	public function getFarmsize($farmid){
		$details = Farm::find()->where(['FarmID'=>$farmid])->one();
		if(count($details)){
			$sizeid = $details['Size'];
			$sizedetails = Size::find()->where(['SizeID'=>$sizeid])->one();
			$size = $sizedetails['Size'];
		}
		else{
			$size = '';
		}
		return $size;
    }
    
    public function getFarmname($farmid){
        $details = Farm::find()->where(['FarmID'=>$farmid])->one();
        if(count($details)){
            $name = $details['FarmName'];
        }
        else{
            $name= "";
        }
        return $name;
    }
	
}

backend/controllers/FarmController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Farm;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Image;
use common\models\StockFarm;
use common\models\FarmImage;
use common\models\Size;
use common\models\FarmStockTransaction;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;
/**
 * FarmController implements the CRUD actions for Farm model.
 */
class FarmController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Farm models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Farm::find()->joinWith(['size'])->where(['Farm.IsDelete'=>0]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Farm model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Farm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Farm();
        $FarmImage=new FarmImage();
        $size=ArrayHelper::map(Size::find()->where(['IsDelete'=>0])->all(),'SizeID','Size');

        if ($model->load(Yii::$app->request->post())) {
            //soil report
            $imagemodel=new Image();
            $sitelogo = UploadedFile::getInstance($model, 'SoilReport');
            if($sitelogo!='')
            {
                $image_id=$imagemodel->pdfUpload($sitelogo,'SoilReport');
				$model->SoilReport=$image_id;
            }
            else
            {
                $model->SoilReport=0;
            }
            
            $model->OnDate=date('Y-m-d H:i:s');
			
			
            $model->AvailableStock=$model->Stock;
            if($model->save())
            {
				/*farm stock management*/
				$stocktransaction = new FarmStockTransaction();
				$stocktransaction->FarmID = $model->FarmID;
				$stocktransaction->StockQTY = $model->Stock;
				$stocktransaction->Type = 0; /*0->Initial Stock Add  1-> Stock Update  2-> Farm Rent*/
				$stocktransaction->UpdateDate = date("Y-m-d H:i:s");
				$stocktransaction->save();
				
				
				for ($x = 0; $x < $model->Stock; $x++) {
					$stocksize = new StockFarm();
					$stocksize->FarmID =  $model->FarmID;
					$stocksize->SizeID =  $model->Size;
					$stocksize->save();
				}
               
                    if($FarmImage->load(Yii::$app->request->post()))
                        {
                            $FarmImage->ImageID = UploadedFile::getInstances($FarmImage,'ImageID');
                            foreach ($FarmImage->ImageID as $file)
                            {
                                $ppimodel=new Image();
                                $ppimageid=$ppimodel->imageUpload($file,'FarmImage');
                                
                                $Farmi=new FarmImage();
                                $Farmi->FarmID=$model->FarmID;
								
                                $Farmi->ImageID=$ppimageid;
                                $Farmi->OnDate=date('Y-m-d H:i:s');
                                if($Farmi->save())
                                {
                                    
                                }
                                else
                                {
                                     $i=1;
                                }
                                //var_dump($banner1->getErrors()).'<br/>';
                            }
                        }
                //farm image
                Yii::$app->session->setFlash('success', 'Farm added successfully');
            }
            else
            {
                var_dump($model->getErrors());
                Yii::$app->session->setFlash('error', 'There is some problem, please try again');
            }
            
        }

        return $this->render('create', [
            'model' => $model,'FarmImage'=>$FarmImage,'size'=>$size
        ]);
    }

    /**
     * Updates an existing Farm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $oldsoilreport=$model->SoilReport;
        $FarmImage=new FarmImage();
        $size=ArrayHelper::map(Size::find()->where(['IsDelete'=>0])->all(),'SizeID','Size');
		$intstock = $model->Stock;
		$farmavailablestock = $model->AvailableStock;
        if ($model->load(Yii::$app->request->post())) {
		
			$updatestock = Yii::$app->request->post()['Farm']['Stock'];
			if($updatestock  > 0){
			    $lateststock =  $updatestock + $farmavailablestock;
				$stock = $intstock + $updatestock;
			}else{
				$lateststock =  $farmavailablestock - $updatestock;
				$stock = $intstock - $updatestock;
			}
			
			if($updatestock>0){
				
				/*Update Latest Stock in the farmstock..*/
				for ($x = 1; $x <= $updatestock; $x++) {
					
					$stocksize = new StockFarm();
					$stocksize->FarmID =  $model->FarmID;
					$stocksize->SizeID =  $model->Size;
					$stocksize->save();
				}
				
				
				$imagemodel=new Image();
				$sitelogo = UploadedFile::getInstance($model, 'SoilReport');
				if($sitelogo!='')
				{
					$image_id=$imagemodel->pdfUpload($sitelogo,'SoilReport');
				}
				else
				{
					$image_id=$oldsoilreport;
				}

				$model->SoilReport=$image_id;
				$model->Stock=$stock;
				$model->AvailableStock=$lateststock;
				
				if($model->save())
				{
					/*farm stock management*/
					$stocktransaction = new FarmStockTransaction();
					$stocktransaction->FarmID = $id;
					$stocktransaction->StockQTY = $updatestock;
					$stocktransaction->Type = 1; /*0->Initial Stock Add  1-> Stock Update  2-> Farm Rent*/
					$stocktransaction->UpdateDate = date("Y-m-d H:i:s");
					$stocktransaction->save();
				
				
				
					if($FarmImage->load(Yii::$app->request->post()))
					{
						$FarmImage->ImageID = UploadedFile::getInstances($FarmImage,'ImageID');
						if($FarmImage->ImageID)
						{
							foreach ($FarmImage->ImageID as $file)
							{
								$ppimodel=new Image();
								$ppimageid=$ppimodel->imageUpload($file,'FarmImage');
								
								$Farmi=new FarmImage();
								$Farmi->FarmID=$model->FarmID;
								$Farmi->ImageID=$ppimageid;
								$Farmi->OnDate=date('Y-m-d H:i:s');
								if($Farmi->save())
								{
									
								}
								else
								{
									 $i=1;
								}
							}
						}
					}
					Yii::$app->session->setFlash('success', 'Farm updated successfully');
					
				}
				else
				{
					Yii::$app->session->setFlash('error', 'There is some problem, please try again');
				}
			}else{
				Yii::$app->session->setFlash('error', 'Stock cannot be negative or zero...Please enter the correct stock');
			}
			
        }

        return $this->render('update', [
            'model' => $model,'FarmImage'=>$FarmImage,'size'=>$size
        ]);
    }

    
    public function actionDelete1($id)
    {
        $model = $this->findModel($id);
		$allfarmimage = FarmImage::find()->where(['FarmID'=>$id])->all();
		if(count($allfarmimage)){
		FarmImage::deleteAll(['and','FarmID' => $id]);
		}
		$soilreportid = $model->SoilReport;
		if($soilreportid!=0){
			$imgdet = Image::find()->where(['ImageID'=>$soilreportid])->one();
			if(count($imgdet)){
				$imgdet->delete();
			}
		}
		$allfarmstockmng = FarmStockTransaction::find()->where(['FarmID'=>$id])->all();
		if(count($allfarmstockmng)){
			//FarmStockTransaction::updateAll(['IsDelete'=>1],"FarmID='$id'");
			FarmStockTransaction::deleteAll(['FarmID' => $id]);
		}
		$model->delete();
        return $this->redirect(['index']);
    }
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
		$model->IsDelete = 1;
		if($model->save()){
			$allfarmstockmng = FarmStockTransaction::find()->where(['FarmID'=>$id])->all();
			if(count($allfarmstockmng)){
				foreach($allfarmstockmng as $stockfarmkey => $stockfarmvalue){
					$deletestockfarm = StockFarm::find()->where(['StockId'=>$stockfarmvalue->StockId])->one();
					$deletestockfarm->IsDelete = 1;
					$deletestockfarm->save();
				}
			}
			FarmStockTransaction::updateAll(['IsDelete' =>1], "FarmID =$id" );
			
			Yii::$app->session->setFlash('success', 'Farm deleted successfully');
		}else{
			Yii::$app->session->setFlash('error', 'There is some problem, please try again');
		}
        return $this->redirect(['index']);
    }
    public function actionFarmimagedelete()
    {
        $farmid=yii::$app->request->get()['farmid'];
        $farmimage=FarmImage::findOne($farmid)->delete();
        return 1;
    }

    /**
     * Finds the Farm model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Farm the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Farm::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/farm/_form.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Farm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="farm-form">

    <?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'FarmName')->textInput() ?>
	
    <?= $form->field($model, 'Size')->dropDownList($size,['prompt'=>'Select...'])?>

    <?= $form->field($model, 'Price')->textInput() ?>

    <?= $form->field($model, 'SoilReport')->fileInput() ?>

    <?= $form->field($model, 'Location')->textarea(['rows' => 6]) ?>

    
	<?= $form->field($model, 'Duration')->dropDownList(
				[
					'1' => '1 Year',
					'2' => '2 Year',
					'3' => '3 Year',
					
				]
			);
	?>
    
    <?= $form->field($model, 'Stock')->textInput() ?>
    <div style="width: 100%;float: left;">
    <?php
    if($model->farmImages)
    {
        foreach($model->farmImages as $fk=>$fval)
        {
    ?>
    <div style="width: 200px;float: left;position: relative;" id="farmimage<?=$fval->FarmImageID;?>">
        <img src="<?=Yii::$app->params['imageurl'].$fval->image->Image;?>" style="height: 150px;"/>
        <span style="position: absolute;font-weight:bold;top: 0px;right: 0px;cursor: pointer;" onclick="farmimagedelete(<?=$fval->FarmImageID;?>);">X</span>
    </div>
    <?php
        }
    }
    ?>
    </div>
    <div id="farmimage">
    <?= $form->field($FarmImage, 'ImageID[]')->fileInput() ?>
    </div>
    <div id="allfarmimage"></div>
    <span class="addmore" onclick="addmore();" style="display:none;">+ Add More</span>
    

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<script type="text/javascript">
    function addmore()
    {
        $('#allfarmimage').append($('#farmimage').html());
    }
    
    function farmimagedelete(farmid)
    {
        $.ajax({url:"<?=Url::toRoute(['farm/farmimagedelete']);?>?farmid="+farmid,
               success:function(results)
                {
                    var res=JSON.parse(results);
                    if(res==1)
                    {
                        alert('Farm Image deleted successfully');
                        $('#farmimage'+farmid).remove();
                    }
                }
        });
    }
</script>

backend/views/farm/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Farm */

$this->title = 'Create Farm';
$this->params['breadcrumbs'][] = ['label' => 'Farms', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="farm-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,'FarmImage'=>$FarmImage,'size'=>$size
    ]) ?>

</div>

backend/views/farm/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Farms';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="farm-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Farm', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
			'FarmName',
            //'FarmID',
             ['attribute'=>'Size',
            'value'=>'size.Size'
            ],
            'Price',
            //'SoilReport',
            //'Location:ntext',
            'Duration',
            //'IsDelete',
            'OnDate',
            //'UpdatedDate',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/farm/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Farm */

$this->title = 'Update Farm: ' . $model->FarmID;
$this->params['breadcrumbs'][] = ['label' => 'Farms', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->FarmID, 'url' => ['view', 'id' => $model->FarmID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="farm-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,'FarmImage'=>$FarmImage,'size'=>$size
    ]) ?>

</div>

backend/views/farm/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Farm */

$this->title = $model->FarmID;
$this->params['breadcrumbs'][] = ['label' => 'Farms', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="farm-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->FarmID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->FarmID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'FarmID',
            'Size',
            'Price',
            'SoilReport',
            'Location:ntext',
            'Duration',
            'IsDelete',
            'OnDate',
            'UpdatedDate',
        ],
    ]) ?>

</div>