common/models/TreePackage.php
<?php

namespace common\models;

use Yii;
use common\models\TreeDetails;
use common\models\TreePackage;
use common\models\TreesImage;
use common\models\TreePlantation;

/**
 * This is the model class for table "TreePackage".
 *
 * @property int $PKGID
 * @property int $TDID
 * @property int $Duration Duration In Month
 * @property int $Quantity Tree Quantity
 * @property double $PlantingCost
 * @property double $MonthlyRecuringCost
 * @property string $CreateDate
 * @property string $UpdateDate
 * @property int $Isdelete
 */
class TreePackage extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'TreePackage';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['PackageName','TDID', 'Duration','PackageCost'], 'required'],
            [['TDID', 'Duration', 'Quantity', 'Isdelete'], 'integer'],
            [['PlantingCost', 'MonthlyRecuringCost'], 'number'],
            [['CreateDate', 'UpdateDate'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
			'PackageName'=>'Package Name',
            'PKGID' => 'Pkgid',
            'TDID' => ' Trees Name',
			'PackageCost'=>'Package Cost',
            'Duration' => 'Package Duration(In Month)',
            'Quantity' => 'Trees Quantity',
            'PlantingCost' => 'Trees Planting Cost',
            'MonthlyRecuringCost' => 'Trees Monthly Recuring Cost',
            'CreateDate' => 'Package Create Date',
            'UpdateDate' => 'Package Update Date',
            'Isdelete' => 'Isdelete',
        ];
    }
	public function getTreename($pkgid){
		$treepkg = TreePackage::find()->where(['PKGID'=>$pkgid])->one();
		if(count($treepkg)){
		   $treeid = $treepkg['TDID'];
		   $treedetails = TreeDetails::find()->where(['ID'=>$treeid])->one();
		   if(count($treedetails)){
			   $treename = $treedetails['TreeName'];
		   }
		}
		else{
			$treename = '';
		}
		
		return $treename;
	}
	public function getTreepackage($pkgid){
		$treepkg = TreePackage::find()->where(['PKGID'=>$pkgid])->one();
		if(count($treepkg)){
		   $pkgname = $treepkg['PackageName'];
		}
		else{
			$pkgname = '';
		}
		
		return $pkgname;
	}
    public function getPackagecost($pkgid){
		$treepkg = TreePackage::find()->where(['PKGID'=>$pkgid])->one();
		if(count($treepkg)){
		   $pkgcost = $treepkg['PackageCost'];
		}
		else{
			$pkgcost = '';
		}
		
		return $pkgcost;
	}
    public function getTreedetail()
    {
        return $this->hasOne(TreeDetails::className(), ['ID' => 'TDID']);
    }
}

backend/controllers/TreePackageController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TreePackage;
use common\models\TreeDetails;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * TreePackageController implements the CRUD actions for TreePackage model.
 */
class TreePackageController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TreePackage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => TreePackage::find()->where(['Isdelete'=>0]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TreePackage model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TreePackage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TreePackage();
		$alltrees=ArrayHelper::map(TreeDetails::find()->where(['IsDelete'=>0])->all(),'ID','TreeName');
		
		
        if ($model->load(Yii::$app->request->post())) {
			
			$model->CreateDate = date("Y-m-d H:i:s A");
			$model->UpdateDate = date("Y-m-d H:i:s A");
			$model->save();
            return $this->redirect(['view', 'id' => $model->PKGID]);
        }

        return $this->render('create', [
            'model' => $model,'alltrees'=>$alltrees
        ]);
    }

    /**
     * Updates an existing TreePackage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $alltrees=ArrayHelper::map(TreeDetails::find()->where(['IsDelete'=>0])->all(),'ID','TreeName'); 
        if ($model->load(Yii::$app->request->post())) {
			
			$model->UpdateDate = date("Y-m-d H:i:s A");
			$model->save();
            return $this->redirect(['view', 'id' => $model->PKGID]);
        }

        return $this->render('update', [
            'model' => $model,'alltrees'=>$alltrees,'treeid'=>$model->TDID
        ]);
    }

    /**
     * Deletes an existing TreePackage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
		$model->Isdelete = 1;
		if($model->save()){
			Yii::$app->session->setFlash('success', 'Tree Package deleted successfully');
		}else{
			Yii::$app->session->setFlash('error', 'There is some problem, please try again');
		}

        return $this->redirect(['index']);
    }

    /**
     * Finds the TreePackage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TreePackage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TreePackage::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
	public function actionTreedetails(){
		$treeid =Yii::$app->request->get()['treesid'];
		$details = TreeDetails::find()->where(['ID'=>$treeid])->one();
		echo "<table class='table' style='width:50%; background:#FFF;'>";
		echo "<tr><th>Planting Cost(Per Unit) : </th>";
		echo "<td> Rs. ".number_format($details['PlantingCost'],2)."<input type='hidden' id='pccost' value='".$details['PlantingCost']."'/></td>";
		echo "</tr><tr><th>Monthly Recuring Cost(Per Unit) : </th>";
		echo "<td> Rs. ".number_format($details['MonthlyRecuringCost'],2)."<input type='hidden' id='mccost' value='".$details['MonthlyRecuringCost']."'/></td>";
		echo "</tr>";
		echo "</table>";
	}
}

backend/views/tree-package/_form.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TreePackage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tree-package-form">

    <?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'PackageName')->textInput() ?>
    
	<?= $form->field($model, 'TDID')->dropDownList($alltrees,['prompt'=>'Select...','onchange'=>'treesDetails(this.value);'])?>
	
	<div class="form-group" id="trees-details" style="display:none; text-align:center;">
		
	</div>

    <?= $form->field($model, 'Duration')->textInput() ?>

    <?php //$form->field($model, 'Quantity')->textInput(['onblur'=>'packageCostcalculation(this.value)']) ?>

    <?php //$form->field($model, 'PlantingCost')->textInput(['readonly'=>'readonly']) ?>

    <?php //$form->field($model, 'MonthlyRecuringCost')->textInput(['readonly'=>'readonly']) ?>
    
	<?= $form->field($model, 'PackageCost')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(event) { 
  <?php 
	if(isset($treeid)){
		?>
		treesDetails(<?=$treeid?>);
		<?php
	}
  ?>
});

function treesDetails(treesid)
    {
		if(treesid!=''){
			$('#trees-details').html('');
			$.ajax({url:"<?=Url::toRoute(['tree-package/treedetails']);?>?treesid="+treesid,
				   success:function(results)
					{
						$('#trees-details').show();
						$('#trees-details').html(results);
					}
			});
		}
		else{
			$('#trees-details').html('');
			$('#trees-details').hide();
		}
	
    }
	function packageCostcalculation(qty){
		if(qty!=''){
			var month = $('#treepackage-duration').val();
			var pccost = $('#pccost').val();
			var rcmcost = $('#mccost').val();
			var totalrcmcost = qty * rcmcost;
			var totalpccost = qty * pccost;
			var totalrecursivecost = month * totalrcmcost;
			
			var total = totalrecursivecost + totalpccost;
			if(!isNaN(totalpccost) && !isNaN(totalrecursivecost)){
				$('#treepackage-plantingcost').val(totalpccost);
				$('#treepackage-monthlyrecuringcost').val(totalrecursivecost);
				$('#treepackage-packagecost').val(total);
			}else{
				$('#treepackage-plantingcost').val();
			    $('#treepackage-monthlyrecuringcost').val();
				$('#treepackage-packagecost').val();
			}
		}
	}
</script>

backend/views/tree-package/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\TreePackage */

$this->title = 'Create Tree Package';
$this->params['breadcrumbs'][] = ['label' => 'Tree Packages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-package-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,'alltrees'=>$alltrees,
    ]) ?>

</div>

backend/views/tree-package/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tree Packages';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-package-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Tree Package', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'PKGID',
            //'TDID',
            'PackageName',
            'PackageCost',
            //'CreateDate',
            //'MonthlyRecuringCost',
            //'CreateDate',
            //'UpdateDate',
            //'Isdelete',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/tree-package/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TreePackage */

$this->title = 'Update Tree Package: ' . $model->PKGID;
$this->params['breadcrumbs'][] = ['label' => 'Tree Packages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->PKGID, 'url' => ['view', 'id' => $model->PKGID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tree-package-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,'alltrees'=>$alltrees,'treeid'=>$treeid
    ]) ?>

</div>

backend/views/tree-package/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\TreePackage */

$this->title = $model->PKGID;
$this->params['breadcrumbs'][] = ['label' => 'Tree Packages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tree-package-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->PKGID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->PKGID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'PackageName',
            [
                'attribute' => 'TDID',
                'value' => $model->treedetail->TreeName,
            ],
            'Duration',
            'CreateDate',
            'UpdateDate',
        ],
    ]) ?>

</div>